AWSTemplateFormatVersion: '2010-09-09'
Description: 'Despliegue de Airflow en Fargate (Con init, worker y DAGs locales) - V5 FINAL'

Parameters:
  VpcId:
    Type: String
  SubnetIds:
    Type: CommaDelimitedList
  SecurityGroupId:
    Type: String
  TaskRoleArn:
    Type: String
  ExecutionRoleArn:
    Type: String
  ImageUri:
    Type: String
  S3DagsPath:
    Type: String # Se mantiene por compatibilidad, pero NO SE USA en la config de Airflow

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/alerta-utec-airflow
      RetentionInDays: 7

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: alerta-utec-airflow-alb
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref SecurityGroupId
      Scheme: internet-facing

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: alerta-utec-airflow-tg
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /health
      Matcher:
        HttpCode: '200'
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 10

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 8081
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # --- Definición de Tarea ---
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: alerta-utec-airflow-task
      Cpu: 2048       # 2 vCPU
      Memory: 8192    # 8 GB RAM (Necesario para 6 contenedores)
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      
      ContainerDefinitions:
        # --- 1. Postgres ---
        - Name: postgres
          Image: postgres:13
          PortMappings:
            - ContainerPort: 5432
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: postgres
          Environment:
            - Name: POSTGRES_USER
              Value: airflow
            - Name: POSTGRES_PASSWORD
              Value: airflow
            - Name: POSTGRES_DB
              Value: airflow
          HealthCheck:
            Command: [ "CMD-SHELL", "pg_isready -U airflow || exit 1" ]
            Interval: 15
            Timeout: 5
            StartPeriod: 120   # 2 min de gracia para arrancar
            Retries: 5

        # --- 2. Redis ---
        - Name: redis
          Image: redis:latest
          PortMappings:
            - ContainerPort: 6379
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: redis
          HealthCheck:
            Command: [ "CMD-SHELL", "redis-cli ping | grep PONG || exit 1" ]
            Interval: 10
            Timeout: 3
            StartPeriod: 30
            Retries: 3
        
        # --- 3. Airflow Init (Inicializa DB y Usuario) ---
        - Name: airflow-init
          Image: !Ref ImageUri
          Essential: false   # Corre una vez y muere (exit 0)
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: airflow-init
          DependsOn:
            - ContainerName: postgres
              Condition: HEALTHY
            - ContainerName: redis
              Condition: HEALTHY
          Environment:
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              Value: postgresql+psycopg2://airflow:airflow@localhost:5432/airflow
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: CeleryExecutor
            - Name: AIRFLOW__CELERY__BROKER_URL
              Value: redis://localhost:6379/0
            - Name: AIRFLOW__CELERY__RESULT_BACKEND
              Value: db+postgresql://airflow:airflow@localhost:5432/airflow
            # --- CORRECCIÓN: Usamos ruta local ---
            - Name: AIRFLOW__CORE__DAGS_FOLDER
              Value: /opt/airflow/dags
            - Name: AIRFLOW__CORE__LOAD_EXAMPLES
              Value: 'False'
          Command:
            - bash
            - -c
            - |
              airflow db migrate
              airflow users create \
                --username airflow \
                --password airflow \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@example.com || true
              echo "Inicialización completa"

        # --- 4. Airflow Webserver ---
        - Name: airflow-webserver
          Image: !Ref ImageUri
          Essential: true
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: airflow-webserver
          DependsOn:
            - ContainerName: airflow-init
              Condition: SUCCESS
          Environment:
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: CeleryExecutor
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              Value: postgresql+psycopg2://airflow:airflow@localhost:5432/airflow
            - Name: AIRFLOW__CELERY__BROKER_URL
              Value: redis://localhost:6379/0
            - Name: AIRFLOW__CELERY__RESULT_BACKEND
              Value: db+postgresql://airflow:airflow@localhost:5432/airflow
            # --- CORRECCIÓN: Usamos ruta local ---
            - Name: AIRFLOW__CORE__DAGS_FOLDER
              Value: /opt/airflow/dags
            - Name: AIRFLOW__CORE__LOAD_EXAMPLES
              Value: 'False'
          Command: [ "webserver" ]

        # --- 5. Airflow Scheduler ---
        - Name: airflow-scheduler
          Image: !Ref ImageUri
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: airflow-scheduler
          DependsOn:
            - ContainerName: airflow-init
              Condition: SUCCESS
          Environment:
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: CeleryExecutor
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              Value: postgresql+psycopg2://airflow:airflow@localhost:5432/airflow
            - Name: AIRFLOW__CELERY__BROKER_URL
              Value: redis://localhost:6379/0
            - Name: AIRFLOW__CELERY__RESULT_BACKEND
              Value: db+postgresql://airflow:airflow@localhost:5432/airflow
            # --- CORRECCIÓN: Usamos ruta local ---
            - Name: AIRFLOW__CORE__DAGS_FOLDER
              Value: /opt/airflow/dags
            - Name: AIRFLOW__CORE__LOAD_EXAMPLES
              Value: 'False'
          Command: [ "scheduler" ]

        # --- 6. Airflow Worker ---
        - Name: airflow-worker
          Image: !Ref ImageUri
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: airflow-worker
          DependsOn:
            - ContainerName: airflow-init
              Condition: SUCCESS
          Environment:
            - Name: AIRFLOW__CORE__EXECUTOR
              Value: CeleryExecutor
            - Name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              Value: postgresql+psycopg2://airflow:airflow@localhost:5432/airflow
            - Name: AIRFLOW__CELERY__BROKER_URL
              Value: redis://localhost:6379/0
            - Name: AIRFLOW__CELERY__RESULT_BACKEND
              Value: db+postgresql://airflow:airflow@localhost:5432/airflow
            # --- CORRECCIÓN: Usamos ruta local ---
            - Name: AIRFLOW__CORE__DAGS_FOLDER
              Value: /opt/airflow/dags
            - Name: AIRFLOW__CORE__LOAD_EXAMPLES
              Value: 'False'
          Command: [ "celery", "worker" ]

  Service:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      ServiceName: alerta-utec-airflow-service
      Cluster: alerta-utec-cluster
      DesiredCount: 1
      LaunchType: FARGATE
      PlatformVersion: LATEST
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref SecurityGroupId
          AssignPublicIp: ENABLED
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerName: airflow-webserver
          ContainerPort: 8080
      HealthCheckGracePeriodSeconds: 600

Outputs:
  AirflowALBDNS:
    Description: "URL pública del ALB de Airflow (http://DNS:8081)"
    Value: !Sub "http://${LoadBalancer.DNSName}:8081"